---
title: "Grammar of schedules"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Todo

- How to do "5th tuesday or thursday of the month"?

## On functions

- On the year
  - `on_year(<int>)`
- On the iso year
  - `on_isoyear(<int>)`
- On the epi year
  - `on_epiyear(<int>)`
  
- On the semester
  - `on_semester_of_year(<int>)`
  - `on_semester()`
  - Restrict to 1:2
  
- On the quarter
  - `on_quarter_of_year(<int>)`
  - `on_quarter(fiscal_start = 1)`
  - Restrict to 1:4
  
- On the month of the year
  - `on_month_of_year(<int/chr>)`
  - `on_month()`
  - `on_ymonth()`
  - Allow December / Dec / 12
- On the month of the quarter
  - `on_month_of_quarter(<int>)`
  - `on_qmonth(<int>)`
  
- On the week of the year
  - `on_week_of_year(<int>)`
  - `on_week()`
  - `on_yweek()`
- On the week of the quarter
  - `on_week_of_quarter(<int>)`
  - `on_qweek(<int>, start = FALSE/TRUE)`
- On the week of the month
  - `on_week_of_month(<int>)`
  - `on_mweek(<int>, start = FALSE/TRUE)`

- On the day of the year
  - `on_day_of_year(<int>)`
  - `on_yday()`
- On the day of the quarter
  - `on_day_of_quarter(<int>)`
  - `on_qday()`
- On the day of the month
  - `on_day_of_month(<int>)`
  - `on_day()`
  - `on_mday(<int>, start = TRUE/FALSE)`
- On the day of the week
  - `on_day_of_week(<int>)`
  - `on_wday()`
  
- On the date
  - `on_date(<date>)`
  
_Maybe_ these

- On hour of the day
  - `on_hour_of_day(<int>)`
  - `on_hour()`

- On minute of the hour
  - `on_minute_of_hour(<int>)`
  - `on_minute()`
  - `on_hminute()`
- On minute of the day
  - `on_minute_of_day()`
  - `on_dminute()`

## After/Before functions

- These are nice because you can say `after_mday(15)` and not have to worry about
  where the end of the month is. Or say `after_mday(2, start = FALSE)` and again
  be able to start from 2 days prior to the end of the month, wherever that is.

- All of these functions should have an `inclusive` boolean parameter as well.

- Before the year
  - `before_year(<int>)`
- Before the iso year
  - `before_isoyear(<int>)`
- Before the epi year
  - `before_epiyear(<int>)`
  
- Before the quarter
  - `before_quarter_of_year(<int>)`
  - `before_quarter(fiscal_start = 1)`
  - Restrict to 1:4
  
- Before the month of the year
  - `before_month_of_year(<int/chr>)`
  - `before_month()`
  - `before_ymonth()`
  - Allow December / Dec / 12
- Before the month of the quarter
  - `before_month_of_quarter(<int>)`
  - `before_qmonth()`
  
- Before the week of the year
  - `before_week_of_year(<int>)`
  - `before_week()`
  - `before_yweek(<int>, start = FALSE/TRUE)`
- Before the week of the quarter
  - `before_week_of_quarter(<int>)`
  - `before_qweek(<int>, start = FALSE/TRUE)`
- Before the week of the month
  - `before_week_of_month(<int>)`
  - `before_mweek(<int>, start = FALSE/TRUE)`

- Before the day of the year
  - `before_day_of_year(<int>)`
  - `before_yday(<int>, start = FALSE/TRUE)`
- Before the day of the quarter
  - `before_day_of_quarter(<int>)`
  - `before_qday(<int>, start = FALSE/TRUE)`
- Before the day of the month
  - `before_day_of_month(<int>)`
  - `before_day(<int>, start = FALSE/TRUE)`
  - `before_mday(<int>, start = TRUE/FALSE)`
- Before the day of the week
  - `before_day_of_week(<int>)`
  - `before_wday(<int>, start = FALSE/TRUE)`
  
- Before the date
  - `before_date(<date>)`
  
## Between functions

- Between two years
  - `between_years(<int>, <int>)`
- Between two isoyears
  - `between_isoyears(<int>, <int>)`
- Between two epiyears
  - `between_epiyears(<int>, <int>)`

- Between two quarters
  - `between_quarters(<int>, <int>)`

- Between two months in a year
  - `between_months(<int/chr>, <int/chr>)`
  - `between_ymonths(<int/chr>, <int/chr>)`
  - Allow normalizing
- Between two months in a quarter
  - `between_qmonths(<int>, <int>)`

- Between two weeks in a year
  - `between_weeks(<int>, <int>)`
  - `between_yweeks(<int>, <int>, start = TRUE/FALSE)`
- Between two weeks in a quarter
  - `between_qweeks(<int>, <int>, start = TRUE/FALSE)`
- Between two weeks in a month
  - `between_mweeks(<int>, <int>, start = TRUE/FALSE)`

- Between two days in a year
  - `between_days(<int>, <int>)`
  - `between_ydays((<int>, <int>)`
- Between two days in a quarter
  - `between_qdays(<int>, <int>)`
- Between two days in a month
  - `between_mdays(<int>, <int>, start = TRUE/FALSE)`
- Between two days in a week
  - `between_wdays(<int>, <int>)`
  - Allow normalizing

- Between two dates
  - `between_dates(<date>, <date>)`

## Miscellaneous

- Before <X> of the <period>, in <Y instance of the period>
  - These can all be generated from existing logic, but helpers for the 
    common ones make it easier
  - For example, "Before 25th day of the month in January"
  - "After 2nd day of the quarter in the 3rd quarter"
  - "Between 12th of January and 25th of October"

- Shortcuts
  - `on_weekdays()`
  - `on_weekends()`


- On N-th occurance of `event` within the `within`
  - `on_count()`
  
- On N-th repeat of `event` since the `since` value
  - `on_repeat()`

- Note:
  - Could these be combined? Is the API really more like:
    `on_repeat(event, n, from, to)`
  - Current `on_repeat()` would be `on_repeat(from = since, to = NULL)`
  - Current `on_count()` would be like `on_repeat(from = "month_start", to = "month_end")`
  - Maybe we could allow:
    - `on_repeat(from = "2000-01-01", to = ~max(.x))`
    - `on_repeat(from = ~floor_date(.x, "month"), to = ~ceiling_date(.x, "month"))`

## N-th functions

- Hopefully not required, and replaceable with `on_wday()` and `on_mweek()`
  
- "On the second monday of the month"
  - `on_wday("Monday") %i% on_mweek(2)`

- "On the last Thursday of the month"
  - `on_wday("Thursday") %i% on_mweek(1, start = FALSE)`

- "On the first Thursday of the quarter"
  - `on_wday("Thursday") %i% on_qweek(1)`

  
  
  
  
  
  
  
  
